# Generated by Django 4.1.4 on 2022-12-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cartitem_unique_together_remove_cartitem_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
